@isTest
private class TestCreateInvoiceBackend {
	private static List<FieloPLT__Program__c> programs;
    private static List<FieloPLT__Member__c> members;
    private static List<FieloPLT__Member__c> products;
    private static List<FieloPRP__Invoice__c> invoices;

    
    /*  TEST-1578
        Create Backend Invoice Page
        - Create Invoice with Items (OK)
    */
    @isTest static void PRP_0010_FB(){
    	
    }
}